scene.setBackgroundColor(10)
let Spongebob = sprites.create(assets.image`Spongebob`, SpriteKind.Player)
let Patrick = sprites.create(assets.image`Patrick`, SpriteKind.Player)
let Squidward = sprites.create(assets.image`Squidward`, SpriteKind.Player)
let Gary = sprites.create(assets.image`Gary`, SpriteKind.Player)
Spongebob.setPosition(36, 32)
Patrick.setPosition(117, 51)
Squidward.setPosition(32, 77)
Gary.setPosition(117, 100)
Spongebob.say("Let's go jellyfishing!")
Patrick.say("To Jellyfish Fields.")
Squidward.say("Get away from me.")
Gary.say("MEEEEOOOOWWWW!")
